FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8000
EXPOSE ${PORT}

# Railway asigna un $PORT dinámico. En local usa 8000 por defecto.
CMD uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
